name: stream_chat_flutter
homepage: https://github.com/GetStream/stream-chat-flutter
description: Stream Chat official Flutter SDK. Build your own chat experience using Dart and Flutter.
version: 0.2.20+2
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  photo_view: ^0.10.1
  rxdart: ^0.24.1
  jiffy: ^3.0.1
  flutter_portal: ^0.3.0
  cached_network_image: ^2.2.0+1
  flutter_markdown: ^0.5.0
  url_launcher: ^5.4.11
  # Video player with custom loadControl for exoplayer
  video_player: #^1.0.0
    git:
      url: https://github.com/ayush221b/plugins.git
      path: packages/video_player/video_player
      ref: f93cfee154c0eea639276669f72283fe9db5b2a9
  # The custom video player
  flick_video_player:
    git:
      url: https://github.com/ayush221b/flick-video-player.git
      ref: b092b0da78e51bad1db7fb76cf2b10d11c7be373
  file_picker: ^2.0.12
  image_picker: ^0.6.7+2
  flutter_keyboard_visibility: ^4.0.1
  stream_chat: ^0.2.21+1
  mime: ^0.9.6+3
  visibility_detector: ^0.1.5
  http_parser: ^3.1.4

dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
